const Portfolio_data = [
  {
    id: 1,
    category: "WEB APPLICATION",
    totalLike: "600",
    title: "Dental APP ",
    githubUrl:"https://github.com/Tanveerhusyn/Dentalapp",
    url:"https://www.youtube.com/watch?v=UrHHrQiUtEg",
    image: "https://www.youtube.com/watch?v=UrHHrQiUtEg",
  },
  {
    id: 2,
    category: "WEB APPLICATION",
    totalLike: "750",
    title: "Brooklyn",
    githubUrl:"https://github.com/Tanveerhusyn",
    url:"https://www.youtube.com/watch?v=JGwifjWQJLw",
    image: "https://images.pexels.com/photos/12328375/pexels-photo-12328375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 3,
    category: "WEB APPLICATION",
    totalLike: "630",
    title: "BINAMARS  ",
    githubUrl:"https://github.com/Tanveerhusyn",
    url:"https://www.youtube.com/watch?v=ChWxkkhI8Bs",
    image: "https://images.pexels.com/photos/12328375/pexels-photo-12328375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 4,
    category: "WEB APPLICATION",
    totalLike: "360",
    title: "Recruitflo",
    githubUrl:"https://github.com/Tanveerhusyn",
    url:"https://www.youtube.com/watch?v=0Cf9JFpYIZM",
    image: "https://images.pexels.com/photos/12328375/pexels-photo-12328375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 5,
    category: "WEB APPLICATION",
    totalLike: "280",
    title: "Saloon",
    githubUrl:"https://github.com/Tanveerhusyn",
    url:"https://www.youtube.com/watch?v=2MHMErUOsyc",
    image: "https://images.pexels.com/photos/12328375/pexels-photo-12328375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
  {
    id: 6,
    category: "WEB APPLICATION",
    totalLike: "690",
    title: "React-Table with Custom Filters",
    githubUrl:"https://github.com/Tanveerhusyn",
    url:"https://www.youtube.com/watch?v=s9cm8tuCqfU",
    image: "https://images.pexels.com/photos/12328375/pexels-photo-12328375.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
  },
]
export default Portfolio_data
